In [27]:
import numpy as np

def backward_probability_recursive(t, i, beta, A, B, x):
    if t == len(x):
        # Base case: When t is the last time step
        print(f"i = {i}, beta[t - 1]: {beta[t - 1]}")
        beta[t - 1][i] = 1
        return 1
    elif beta[t - 1][i] != 0:
        # If the value is already calculated, return it
        return beta[t - 1][i]
    else:
        # Recursive case: When t < T
        summation = 0
        for j in range(A.shape[0]):
            if t < len(x):  # Check bounds to prevent out-of-bounds error
                summation += A[i][j] * B[j][x[t]] * backward_probability_recursive(t + 1, j, beta, A, B, x)
        beta[t - 1][i] = summation  # Store the calculated value in the beta matrix
        return summation

# Example usage:

# Define the values of w, A, B, and the observed sequence x as NumPy arrays
w = np.array([0.3, 0.7])
A = np.array([[0.2, 0.8], [0.6, 0.4]])  # Ensure A has the correct shape
B = np.array([[0.1, 0.4, 0.5], [0.7, 0.2, 0.1]])  # Ensure B has the correct shape
x = np.array([2, 3, 3, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 1, 1, 3, 3, 3, 2, 3, 3, 3, 1, 3, 1, 1, 1, 2, 2, 3, 3, 3, 3, 3, 1, 3,
 2, 2, 3, 3, 3, 3, 1, 1, 3, 3, 3, 2, 3, 3, 1, 3, 1, 3, 3, 3, 2, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 3,
 3, 1, 2, 1, 3, 1, 1, 3, 1, 1, 2, 1, 3, 1, 1, 2, 1, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 2, 3, 3, 2, 3, 2, 3, 1, 3,
 3, 3, 3, 1, 2, 2, 3, 3, 3, 3, 1, 2, 2, 2, 1, 3, 1, 3, 1, 1, 3, 1, 2, 3, 3, 3, 2, 2, 3, 1, 3, 1, 2, 1, 2, 1, 3,
 1, 3, 1, 3, 3, 3, 1, 1, 3, 2, 3, 1, 3, 3, 2, 3, 3, 1, 1, 1, 2, 3, 1, 1, 2, 1, 3, 3, 3, 1, 2, 1, 3, 2, 3, 3, 3,
 3, 3, 2, 1, 2, 2, 3, 1, 2, 3, 2, 3, 2, 2])

# Define the time step 't' and the hidden state 'i' for which you want to calculate βt(i)
t = len(x)  # For example, calculate βt(200)
i = 2  # Set 'i' to the desired hidden state index

# Initialize the beta array
beta = np.zeros((len(x), A.shape[0]))

# Calculate βt(i) using the recursive function
beta_t_i = backward_probability_recursive(t, i-1, beta, A, B, x)

print("β{}({}) = {}".format(t, i-1, beta_t_i))


i = 1, beta[t - 1]: [0. 0.]
β198(1) = 1


In [28]:
beta

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.

In [15]:
beta1 = np.zeros((len(x), A.shape[0]))

for t in range(len(x)):
    for i in range(w.shape[0]):
        backward_probability_recursive(t, i-1, beta1, A, B, x)

IndexError: index 3 is out of bounds for axis 0 with size 3

200
t= 1, i = 1
In ELSE : i : 1
t= 2, i = -1
In ELSE : i : -1
t= 3, i = -1
In ELSE : i : -1
t= 4, i = -1
In ELSE : i : -1
t= 5, i = -1
In ELSE : i : -1
t= 6, i = -1
In ELSE : i : -1
t= 7, i = -1
In ELSE : i : -1
t= 8, i = -1
In ELSE : i : -1
t= 9, i = -1
In ELSE : i : -1
t= 10, i = -1
In ELSE : i : -1
t= 11, i = -1
In ELSE : i : -1
t= 12, i = -1
In ELSE : i : -1
t= 13, i = -1
In ELSE : i : -1
t= 14, i = -1
In ELSE : i : -1
t= 15, i = -1
In ELSE : i : -1
t= 16, i = -1
In ELSE : i : -1
t= 17, i = -1
In ELSE : i : -1
t= 18, i = -1
In ELSE : i : -1
t= 19, i = -1
In ELSE : i : -1
t= 20, i = -1
In ELSE : i : -1
t= 21, i = -1
In ELSE : i : -1
t= 22, i = -1
In ELSE : i : -1
t= 23, i = -1
In ELSE : i : -1
t= 24, i = -1
In ELSE : i : -1
t= 25, i = -1
In ELSE : i : -1
t= 26, i = -1
In ELSE : i : -1
t= 27, i = -1
In ELSE : i : -1
t= 28, i = -1
In ELSE : i : -1
t= 29, i = -1
In ELSE : i : -1
t= 30, i = -1
In ELSE : i : -1
t= 31, i = -1
In ELSE : i : -1
t= 32, i = -1
In ELSE : i : -1
t= 33, i = -1
I

In [32]:
beta

array([[0.00000000e+00, 4.73126577e-97],
       [2.07800367e-96, 1.39853836e-96],
       [7.19073053e-96, 4.83547264e-96],
       [2.48021475e-95, 1.67367189e-95],
       [8.67129044e-95, 5.76697234e-95],
       [2.86265425e-94, 2.02468990e-94],
       [1.18672554e-93, 6.56327285e-94],
       [1.25929026e-93, 2.90384935e-93],
       [6.49772633e-93, 4.37010721e-93],
       [2.24248810e-92, 1.51230718e-92],
       [7.82126254e-92, 5.21515712e-92],
       [2.60905171e-91, 1.82486305e-91],
       [1.04067439e-90, 6.00229207e-91],
       [1.59784022e-90, 2.52179397e-90],
       [4.92249674e-90, 1.13586335e-89],
       [2.54211003e-89, 1.70442837e-89],
       [8.66746721e-89, 5.92190171e-89],
       [3.17633621e-88, 2.00804999e-88],
       [8.39763772e-88, 7.52095864e-88],
       [3.32213978e-87, 2.20899431e-87],
       [1.09584884e-86, 7.75742504e-87],
       [4.55636164e-86, 2.51180403e-86],
       [4.67246418e-86, 1.11572809e-85],
       [2.52029966e-85, 1.43005583e-85],
       [3.398119

In [36]:
import numpy as np

def backward_probability_recursive(t, i, beta, A, B, x):
    print(f"t: {t}, i:{i}, len(x): {len(x)}")
    if t == len(x):
        print(f"1st if: t: {t}, i:{i}")
        # Base case: When t is the last time step
        beta[t - 1][i] = 1
        return 1
    elif t < len(x) and beta[t - 1][i] != 0:  # Check bounds to prevent out-of-bounds error
        print(f"2nd if: t: {t}, i:{i}")
        # If the value is already calculated, return it
        return beta[t - 1][i]
    else:
        print(f"else: t: {t}, i:{i}")
        # Recursive case: When t < T
        summation = 0
        for j in range(A.shape[0]):
            if t < len(x):  # Check bounds to prevent out-of-bounds error
                summation += A[i][j] * B[j][x[t]] * backward_probability_recursive(t + 1, j, beta, A, B, x)
        beta[t - 1][i] = summation  # Store the calculated value in the beta matrix
        return summation

# Example usage:

# Define the values of w, A, B, and the observed sequence x as NumPy arrays
w = np.array([0.3, 0.7])
A = np.array([[0.2, 0.8], [0.6, 0.4]])  # Ensure A has the correct shape
B = np.array([[0.1, 0.4, 0.5], [0.7, 0.2, 0.1]])  # Ensure B has the correct shape
x = np.array([2, 3, 3, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 1, 1, 3, 3, 3, 2, 3, 3, 3, 1, 3, 1, 1, 1, 2, 2, 3, 3, 3, 3, 3, 1, 3,
 2, 2, 3, 3, 3, 3, 1, 1, 3, 3, 3, 2, 3, 3, 1, 3, 1, 3, 3, 3, 2, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 3,
 3, 1, 2, 1, 3, 1, 1, 3, 1, 1, 2, 1, 3, 1, 1, 2, 1, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 2, 3, 3, 2, 3, 2, 3, 1, 3,
 3, 3, 3, 1, 2, 2, 3, 3, 3, 3, 1, 2, 2, 2, 1, 3, 1, 3, 1, 1, 3, 1, 2, 3, 3, 3, 2, 2, 3, 1, 3, 1, 2, 1, 2, 1, 3,
 1, 3, 1, 3, 3, 3, 1, 1, 3, 2, 3, 1, 3, 3, 2, 3, 3, 1, 1, 1, 2, 3, 1, 1, 2, 1, 3, 3, 3, 1, 2, 1, 3, 2, 3, 3, 3,
 3, 3, 2, 1, 2, 2, 3, 1, 2, 3, 2, 3, 2, 2,1,1])

# Define the time step 't' and the hidden state 'i' for which you want to calculate βt(i)
t = 200  # For example, calculate βt(200)
i = 1  # Set 'i' to the desired hidden state index

# Initialize the beta array
beta = np.zeros((len(x), A.shape[0]))

# Calculate βt(i) using the recursive function
beta_t_i = backward_probability_recursive(t, i, beta, A, B, x)

print("β{}({}) = {}".format(t, i, beta_t_i))


t: 200, i:1, len(x): 200
1st if: t: 200, i:1
β200(1) = 1


In [41]:
import numpy as np

def backward_probability_recursive(t, i, beta, A, B, x):
    print(f"t: {t}, i:{i}, len(x): {len(x)}")
    
    if t == 1:
        print(f"1st if: t: {t}, i:{i}")
        # Base case: When t is the first time step
        return 1
    elif beta[t - 1][i] != 0:
        print(f"2st if: t: {t}, i:{i}")
        # If the value is already calculated, return it
        return beta[t - 1][i]
    else:
        print(f"else: t: {t}, i:{i}")
        # Recursive case: When t > 1
        summation = 0
        for j in range(A.shape[0]):
            print(f"else-j : {j}")
            summation += A[i][j] * B[j][x[t - 1]] * backward_probability_recursive(t - 1, j, beta, A, B, x)
        beta[t - 1][i] = summation  # Store the calculated value in the beta matrix
        return summation

# Example usage:

# Define the values of w, A, B, and the observed sequence x as NumPy arrays
w = np.array([0.3, 0.7])
A = np.array([[0.2, 0.8], [0.6, 0.4]])  # Ensure A has the correct shape
B = np.array([[0.1, 0.4, 0.5], [0.7, 0.2, 0.1]])  # Ensure B has the correct shape
x = np.array([2, 3, 3, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 1, 1, 3, 3, 3, 2, 3, 3, 3, 1, 3, 1, 1, 1, 2, 2, 3, 3, 3, 3, 3, 1, 3,
 2, 2, 3, 3, 3, 3, 1, 1, 3, 3, 3, 2, 3, 3, 1, 3, 1, 3, 3, 3, 2, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 3,
 3, 1, 2, 1, 3, 1, 1, 3, 1, 1, 2, 1, 3, 1, 1, 2, 1, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 2, 3, 3, 2, 3, 2, 3, 1, 3,
 3, 3, 3, 1, 2, 2, 3, 3, 3, 3, 1, 2, 2, 2, 1, 3, 1, 3, 1, 1, 3, 1, 2, 3, 3, 3, 2, 2, 3, 1, 3, 1, 2, 1, 2, 1, 3,
 1, 3, 1, 3, 3, 3, 1, 1, 3, 2, 3, 1, 3, 3, 2, 3, 3, 1, 1, 1, 2, 3, 1, 1, 2, 1, 3, 3, 3, 1, 2, 1, 3, 2, 3, 3, 3,
 3, 3, 2, 1, 2, 2, 3, 1, 2, 3, 2, 3, 2, 2,1,1])

# Define the time step 't' and the hidden state 'i' for which you want to calculate βt(i)
t = 200  # For example, calculate βt(200)
i = 1  # Set 'i' to the desired hidden state index

# Initialize the beta array with 1 in the last row
beta = np.zeros((len(x), A.shape[0]))
beta[-1] = 1

# Calculate βt(i) using the recursive function
beta_t_i = backward_probability_recursive(t, i, beta, A, B, x)

print("β{}({}) = {}".format(t, i, beta_t_i))


t: 200, i:1, len(x): 200
2st if: t: 200, i:1
β200(1) = 1.0


In [42]:
beta

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.

In [51]:
import numpy as np

def backward_probability_recursive(t, i, beta, A, B, x):
    print(f"t: {t}, i:{i}, len(x): {len(x)}")
    if t == len(x):
        print(f"1st if: t: {t}, i:{i}")
        # Base case: When t is the last time step
        beta[t - 1] = 1
        return 1
    elif beta[t-1][i] != 0:
        
        print(f"2st if: t: {t}, i:{i}")
        # If the value is already calculated, return it
        return beta[t][i]
    else:
        # Recursive case: When t < T
        print(f"Recursive case: When t={t} < {len(x)} => i:{i} ,x:{len(x)}")
        summation = 0
        for j in range(A.shape[0]):
            print(f"j:{j}, x[t]: {x[t]}")
            summation += A[i][j] * B[j][x[t]-1] * backward_probability_recursive(t + 1, j, beta, A, B, x)
        beta[t][i] = summation  # Store the calculated value in the beta matrix
        return summation

# Example usage:

# Define the values of w, A, B, and the observed sequence x as NumPy arrays
w = np.array([0.3, 0.7])
A = np.array([[0.2, 0.8], [0.6, 0.4]])  # Ensure A has the correct shape
B = np.array([[0.1, 0.4, 0.5], [0.7, 0.2, 0.1]])  # Ensure B has the correct shape
x = np.array([2, 3, 3, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 1, 1, 3, 3, 3, 2, 3, 3, 3, 1, 3, 1, 1, 1, 2, 2, 3, 3, 3, 3, 3, 1, 3,
 2, 2, 3, 3, 3, 3, 1, 1, 3, 3, 3, 2, 3, 3, 1, 3, 1, 3, 3, 3, 2, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 3,
 3, 1, 2, 1, 3, 1, 1, 3, 1, 1, 2, 1, 3, 1, 1, 2, 1, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 2, 3, 3, 2, 3, 2, 3, 1, 3,
 3, 3, 3, 1, 2, 2, 3, 3, 3, 3, 1, 2, 2, 2, 1, 3, 1, 3, 1, 1, 3, 1, 2, 3, 3, 3, 2, 2, 3, 1, 3, 1, 2, 1, 2, 1, 3,
 1, 3, 1, 3, 3, 3, 1, 1, 3, 2, 3, 1, 3, 3, 2, 3, 3, 1, 1, 1, 2, 3, 1, 1, 2, 1, 3, 3, 3, 1, 2, 1, 3, 2, 3, 3, 3,
 3, 3, 2, 1, 2, 2, 3, 1, 2, 3, 2, 3, 2, 2,1,1])

# Define the time step 't' and the hidden state 'i' for which you want to calculate βt(i)
t = 1  # For example, calculate βt(1)
i = 0  # Set 'i' to the desired hidden state index

# Initialize the beta array with 1 in the last row
beta = np.zeros((len(x), A.shape[0]))

# Calculate βt(i) using the recursive function
beta_t_i = backward_probability_recursive(t, i, beta, A, B, x)

print("β{}({}) = {}".format(t, i, beta_t_i))


t: 1, i:0, len(x): 200
Recursive case: When t=1 < 200 => i:0 ,x:200
j:0, x[t]: 3
t: 2, i:0, len(x): 200
Recursive case: When t=2 < 200 => i:0 ,x:200
j:0, x[t]: 3
t: 3, i:0, len(x): 200
Recursive case: When t=3 < 200 => i:0 ,x:200
j:0, x[t]: 3
t: 4, i:0, len(x): 200
Recursive case: When t=4 < 200 => i:0 ,x:200
j:0, x[t]: 3
t: 5, i:0, len(x): 200
Recursive case: When t=5 < 200 => i:0 ,x:200
j:0, x[t]: 3
t: 6, i:0, len(x): 200
Recursive case: When t=6 < 200 => i:0 ,x:200
j:0, x[t]: 3
t: 7, i:0, len(x): 200
Recursive case: When t=7 < 200 => i:0 ,x:200
j:0, x[t]: 1
t: 8, i:0, len(x): 200
Recursive case: When t=8 < 200 => i:0 ,x:200
j:0, x[t]: 3
t: 9, i:0, len(x): 200
Recursive case: When t=9 < 200 => i:0 ,x:200
j:0, x[t]: 3
t: 10, i:0, len(x): 200
Recursive case: When t=10 < 200 => i:0 ,x:200
j:0, x[t]: 3
t: 11, i:0, len(x): 200
Recursive case: When t=11 < 200 => i:0 ,x:200
j:0, x[t]: 3
t: 12, i:0, len(x): 200
Recursive case: When t=12 < 200 => i:0 ,x:200
j:0, x[t]: 3
t: 13, i:0, len(x): 20

t: 87, i:1, len(x): 200
2st if: t: 87, i:1
j:1, x[t]: 2
t: 84, i:1, len(x): 200
Recursive case: When t=84 < 200 => i:1 ,x:200
j:0, x[t]: 1
t: 85, i:0, len(x): 200
2st if: t: 85, i:0
j:1, x[t]: 1
t: 85, i:1, len(x): 200
Recursive case: When t=85 < 200 => i:1 ,x:200
j:0, x[t]: 3
t: 86, i:0, len(x): 200
2st if: t: 86, i:0
j:1, x[t]: 3
t: 86, i:1, len(x): 200
2st if: t: 86, i:1
j:1, x[t]: 1
t: 83, i:1, len(x): 200
Recursive case: When t=83 < 200 => i:1 ,x:200
j:0, x[t]: 2
t: 84, i:0, len(x): 200
2st if: t: 84, i:0
j:1, x[t]: 2
t: 84, i:1, len(x): 200
Recursive case: When t=84 < 200 => i:1 ,x:200
j:0, x[t]: 1
t: 85, i:0, len(x): 200
2st if: t: 85, i:0
j:1, x[t]: 1
t: 85, i:1, len(x): 200
2st if: t: 85, i:1
j:1, x[t]: 1
t: 82, i:1, len(x): 200
Recursive case: When t=82 < 200 => i:1 ,x:200
j:0, x[t]: 1
t: 83, i:0, len(x): 200
2st if: t: 83, i:0
j:1, x[t]: 1
t: 83, i:1, len(x): 200
Recursive case: When t=83 < 200 => i:1 ,x:200
j:0, x[t]: 2
t: 84, i:0, len(x): 200
2st if: t: 84, i:0
j:1, x[t]: 

In [50]:
beta

array([[0.00000000e+000, 0.00000000e+000],
       [7.76485383e-103, 0.00000000e+000],
       [3.39424636e-102, 5.46325933e-102],
       [1.50645446e-101, 2.35973988e-101],
       [6.42605058e-101, 1.07981175e-100],
       [3.03403690e-100, 4.24001711e-100],
       [1.08919947e-099, 2.43104679e-099],
       [7.54578822e-099, 4.18275805e-099],
       [8.19727887e-099, 1.31818619e-098],
       [3.63328897e-098, 5.70498738e-098],
       [1.55533716e-097, 2.59743976e-097],
       [7.27908472e-097, 1.03428586e-096],
       [2.68132650e-096, 5.74719777e-096],
       [1.76261381e-095, 1.14839086e-095],
       [5.34167907e-095, 2.95675041e-095],
       [5.71821748e-095, 9.33449057e-095],
       [2.59015273e-094, 3.91008093e-094],
       [1.04600183e-093, 1.93018863e-093],
       [5.62875087e-093, 6.03908424e-093],
       [1.61235440e-092, 2.71179210e-092],
       [7.62245957e-092, 1.06263556e-091],
       [2.72605031e-091, 6.12051158e-091],
       [1.90299457e-090, 1.02881968e-090],
       [1.5

In [52]:
import numpy as np

def backward_probability_recursive(t, i, beta, A, B, x):
    if t == len(x):
        # Base case: When t is the last time step
        return 1
    elif beta[t][i] != 0:
        # If the value is already calculated, return it
        return beta[t][i]
    else:
        # Recursive case: When t < T
        summation = 0
        for j in range(A.shape[0]):
            summation += A[i][j] * B[j][x[t]] * backward_probability_recursive(t + 1, j, beta, A, B, x)
        beta[t][i] = summation  # Store the calculated value in the beta matrix
        return summation

# Example usage:

# Define the values of w, A, B, and the observed sequence x as NumPy arrays
w = np.array([0.3, 0.7])
A = np.array([[0.2, 0.8], [0.6, 0.4]])  # Ensure A has the correct shape
B = np.array([[0.1, 0.4, 0.5], [0.7, 0.2, 0.1]])  # Ensure B has the correct shape
x = np.array([2, 3, 3, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 1, 1, 3, 3, 3, 2, 3, 3, 3, 1, 3, 1, 1, 1, 2, 2, 3, 3, 3, 3, 3, 1, 3,
 2, 2, 3, 3, 3, 3, 1, 1, 3, 3, 3, 2, 3, 3, 1, 3, 1, 3, 3, 3, 2, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 3,
 3, 1, 2, 1, 3, 1, 1, 3, 1, 1, 2, 1, 3, 1, 1, 2, 1, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 2, 3, 3, 2, 3, 2, 3, 1, 3,
 3, 3, 3, 1, 2, 2, 3, 3, 3, 3, 1, 2, 2, 2, 1, 3, 1, 3, 1, 1, 3, 1, 2, 3, 3, 3, 2, 2, 3, 1, 3, 1, 2, 1, 2, 1, 3,
 1, 3, 1, 3, 3, 3, 1, 1, 3, 2, 3, 1, 3, 3, 2, 3, 3, 1, 1, 1, 2, 3, 1, 


SyntaxError: unexpected EOF while parsing (<ipython-input-52-b30de8bc278e>, line 28)

In [109]:
import numpy as np

def backward_probability_recursive1(t, w, beta, A, B, x):
    print(f"---[New Iteration]-----\nt: {t}, w:{len(w)}, len(x): {len(x)}, A_shape={ A.shape}")
#     if t == len(x):
#         print(f"1st if: t: {t}, i:{i}")
#         # Base case: When t is the last time step
#         beta[t-1] =1
#         return 1
    #i = i-1
    if t < 0:
        return 1
#     elif beta[t-1][i] != 0:
#         print(f"2st if: t: {t}, i:{i}")
#         # If the value is already calculated, return it
#         return beta[t][i]
    else:
        print(f"Recursive case: When t={t} < {len(x)} ,x:{len(x)}")
        # Recursive case: When t < T
        summation = 0
        if t == len(x):
            print(f"1st if: t: {t}, ")
            # Base case: When t is the last time step
            beta[t-1] =1
            return backward_probability_recursive1(t - 1, w, beta, A, B, x)
        else:
            #print(f"when t not 200 => t:{t}, beta[t+1] = beta[{t}+1] = beta[{t}]: {beta[t]}")
            t = (t-1)
           
            print(f"updated_index: {t} , beta[t+1] = beta[{t}+1] = beta[{t+1}]: {beta[t+1]}")
            if t < 0:
                return 1
            
            for i in range(w.shape[0]):
                
                for j in range(A.shape[0]):

                    #print(f"j:{j},t={t},i={i}, x[t]=x[{t}]: {x[t]}, (beta[t+1][j] = beta[{t+1}][{j}]) ={beta[t+1][j]}")
                    summation += A[i][j] * B[j][x[t]-1] * beta[t+1][j]


                # call recursively by updating the value of t
                beta[t][i] = summation  # Store the calculated value in the beta matrix
                print(f"t={t}, i ={i}, beta[t][i] = beta[{t}][{i}]  =>{beta[t][j]}")
                
            
            #t = (t+1) # convert the index to row number before sending to recorsive function
            return backward_probability_recursive1(t , w, beta, A, B, x)
            
        
#         for j in range(A.shape[0]):
#             print(f"j:{j}, x[t]: {x[t]}, beta[t][j] ={beta[t][j]}")
#             summation += A[i][j] * B[j][x[t]-1] * beta[t][j]
#         beta[t][i] = summation  # Store the calculated value in the beta matrix
        
#         backward_probability_recursive(t - 1, j, beta, A, B, x)
        return summation

# Example usage:

# Define the values of w, A, B, and the observed sequence x as NumPy arrays
w = np.array([0.3, 0.7])
A = np.array([[0.2, 0.8], [0.6, 0.4]])  # Ensure A has the correct shape
B = np.array([[0.1, 0.4, 0.5], [0.7, 0.2, 0.1]])  # Ensure B has the correct shape
x = np.array([2, 3, 3, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 1, 1, 3, 3, 3, 2, 3, 3, 3, 1, 3, 1, 1, 1, 2, 2, 3, 3, 3, 3, 3, 1, 3,
 2, 2, 3, 3, 3, 3, 1, 1, 3, 3, 3, 2, 3, 3, 1, 3, 1, 3, 3, 3, 2, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 3,
 3, 1, 2, 1, 3, 1, 1, 3, 1, 1, 2, 1, 3, 1, 1, 2, 1, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 2, 3, 3, 2, 3, 2, 3, 1, 3,
 3, 3, 3, 1, 2, 2, 3, 3, 3, 3, 1, 2, 2, 2, 1, 3, 1, 3, 1, 1, 3, 1, 2, 3, 3, 3, 2, 2, 3, 1, 3, 1, 2, 1, 2, 1, 3,
 1, 3, 1, 3, 3, 3, 1, 1, 3, 2, 3, 1, 3, 3, 2, 3, 3, 1, 1, 1, 2, 3, 1, 1, 2, 1, 3, 3, 3, 1, 2, 1, 3, 2, 3, 3, 3,
 3, 3, 2, 1, 2, 2, 3, 1, 2, 3, 2, 3, 2, 2,1,1])

# Define the time step 't' and the hidden state 'i' for which you want to calculate βt(i)
t = len(x)  # Calculate βt(T) for the last time step
i = 2  # Set 'i' to the desired hidden state index

# Initialize the beta array
beta = np.zeros((len(x), A.shape[0]))
beta[t-1] = 1
# Calculate βt(i) using the recursive function
#beta_t_i = backward_probability_recursive(t, i, beta, A, B, x)

beta_199_0 = backward_probability_recursive1(200, w, beta, A, B, x)


print("β{}({}) = {}".format(t, i, beta_199_0))


---[New Iteration]-----
t: 200, w:2, len(x): 200, A_shape=(2, 2)
Recursive case: When t=200 < 200 ,x:200
1st if: t: 200, 
---[New Iteration]-----
t: 199, w:2, len(x): 200, A_shape=(2, 2)
Recursive case: When t=199 < 200 ,x:200
updated_index: 198 , beta[t+1] = beta[198+1] = beta[199]: [1. 1.]
t=198, i =0, beta[t][i] = beta[198][0]  =>0.0
t=198, i =1, beta[t][i] = beta[198][1]  =>0.9199999999999999
---[New Iteration]-----
t: 198, w:2, len(x): 200, A_shape=(2, 2)
Recursive case: When t=198 < 200 ,x:200
updated_index: 197 , beta[t+1] = beta[197+1] = beta[198]: [0.58 0.92]
t=197, i =0, beta[t][i] = beta[197][0]  =>0.0
t=197, i =1, beta[t][i] = beta[197][1]  =>0.4064
---[New Iteration]-----
t: 197, w:2, len(x): 200, A_shape=(2, 2)
Recursive case: When t=197 < 200 ,x:200
updated_index: 196 , beta[t+1] = beta[196+1] = beta[197]: [0.1936 0.4064]
t=196, i =0, beta[t][i] = beta[196][0]  =>0.0
t=196, i =1, beta[t][i] = beta[196][1]  =>0.15948800000000005
---[New Iteration]-----
t: 196, w:2, len(x)

In [110]:
beta

array([[3.45107640e-71, 6.68265148e-71],
       [7.53018444e-71, 1.78041353e-70],
       [2.60354345e-70, 6.15830124e-70],
       [9.01194426e-70, 2.12793628e-69],
       [3.10457855e-69, 7.38420714e-69],
       [1.09093573e-68, 2.51705352e-68],
       [3.52259970e-68, 9.23344699e-68],
       [1.57981898e-67, 2.42847591e-67],
       [1.17494892e-67, 2.77914285e-67],
       [4.06687791e-67, 9.60326407e-67],
       [1.40117888e-66, 3.33212379e-66],
       [4.92142188e-66, 1.13629586e-65],
       [1.59233032e-65, 4.16136445e-65],
       [7.09147585e-65, 1.10397842e-64],
       [8.05140917e-65, 1.23757994e-64],
       [5.97371324e-65, 1.41641695e-64],
       [2.08143985e-64, 4.86534174e-64],
       [6.97272788e-64, 1.73020882e-63],
       [2.73719856e-63, 5.29441166e-63],
       [5.94306913e-63, 1.41359564e-62],
       [2.08854109e-62, 4.81816005e-62],
       [6.74139366e-62, 1.76800215e-61],
       [3.02717241e-61, 4.64277657e-61],
       [2.04035912e-61, 5.33279505e-61],
       [9.089025

In [111]:
beta.shape

(200, 2)

In [112]:
beta[199]

array([1., 1.])

In [145]:
def backward_probability_recursive2(t, w, beta, A, B, x):
    print(f"====[New Iteration]====\nt: {t}, w:{len(w)}, len(x): {len(x)}, A_shape={ A.shape}")

    if t < 0:
        return 1

    else:
        print(f"Recursive case: When t={t} < {len(x)} ,x:{len(x)}")
        # Recursive case: When t < T
        summation = 0
        if t == len(x):
            print(f"1st if: t: {t}, ")
            # Base case: When t is the last time step
            beta[t-1] =1
            return backward_probability_recursive2(t - 1, w, beta, A, B, x)
        else:
            #print(f"when t not 200 => t:{t}, beta[t+1] = beta[{t}+1] = beta[{t}]: {beta[t]}")
            t = (t-1)
           
            print(f"updated_index: {t} , beta[t+1] = beta[{t}+1] = beta[{t+1}]: {beta[t+1]}")
            if t < 0:
                return 1
            
            for i in range(w.shape[0]):
                print(f"---new i :{i} fot index t= {t}--")
                
                for j in range(A.shape[0]):

                    print(f"j:{j},t={t},i={i},A[i][j]={A[i][j]} ,B[j]: {B[j]},B_{j}_{x[t]-1}={B[j][x[t]-1]} x[t]=x[{t}]: {x[t]}, (beta[t+1][j] = beta[{t+1}][{j}]) ={beta[t+1][j]}")
                    summation += A[i][j] * B[j][x[t]-1] * beta[t+1][j]
                    print(f"summation_{i}_{j}= {summation}")


                # call recursively by updating the value of t
                beta[t][i] = summation  # Store the calculated value in the beta matrix
                print(f"t={t}, i ={i}, beta[t][i] = beta[{t}][{i}]  =>{beta[t][j]}")
                
            
            #t = (t+1) # convert the index to row number before sending to recorsive function
            return backward_probability_recursive2(t , w, beta, A, B, x)
            

#         return beta


In [146]:
beta2 = np.zeros((len(x), A.shape[0]))
backward_probability_recursive2(200, w, beta2, A, B, x)

====[New Iteration]====
t: 200, w:2, len(x): 200, A_shape=(2, 2)
Recursive case: When t=200 < 200 ,x:200
1st if: t: 200, 
====[New Iteration]====
t: 199, w:2, len(x): 200, A_shape=(2, 2)
Recursive case: When t=199 < 200 ,x:200
updated_index: 198 , beta[t+1] = beta[198+1] = beta[199]: [1. 1.]
---new i :0 fot index t= 198--
j:0,t=198,i=0,A[i][j]=0.2 ,B[j]: [0.1 0.4 0.5],B_0_0=0.1 x[t]=x[198]: 1, (beta[t+1][j] = beta[199][0]) =1.0
summation_0_0= 0.020000000000000004
j:1,t=198,i=0,A[i][j]=0.8 ,B[j]: [0.7 0.2 0.1],B_1_0=0.7 x[t]=x[198]: 1, (beta[t+1][j] = beta[199][1]) =1.0
summation_0_1= 0.58
t=198, i =0, beta[t][i] = beta[198][0]  =>0.0
---new i :1 fot index t= 198--
j:0,t=198,i=1,A[i][j]=0.6 ,B[j]: [0.1 0.4 0.5],B_0_0=0.1 x[t]=x[198]: 1, (beta[t+1][j] = beta[199][0]) =1.0
summation_1_0= 0.6399999999999999
j:1,t=198,i=1,A[i][j]=0.4 ,B[j]: [0.7 0.2 0.1],B_1_0=0.7 x[t]=x[198]: 1, (beta[t+1][j] = beta[199][1]) =1.0
summation_1_1= 0.9199999999999999
t=198, i =1, beta[t][i] = beta[198][1]  =>0

summation_0_1= 6.248590807369812e-45
t=67, i =0, beta[t][i] = beta[67][0]  =>0.0
---new i :1 fot index t= 67--
j:0,t=67,i=1,A[i][j]=0.6 ,B[j]: [0.1 0.4 0.5],B_0_2=0.5 x[t]=x[67]: 3, (beta[t+1][j] = beta[68][0]) =2.0215916587152607e-44
summation_1_0= 1.2313365783515595e-44
j:1,t=67,i=1,A[i][j]=0.4 ,B[j]: [0.7 0.2 0.1],B_1_2=0.1 x[t]=x[67]: 3, (beta[t+1][j] = beta[68][1]) =5.283748935818188e-44
summation_1_1= 1.442686535784287e-44
t=67, i =1, beta[t][i] = beta[67][1]  =>1.442686535784287e-44
====[New Iteration]====
t: 67, w:2, len(x): 200, A_shape=(2, 2)
Recursive case: When t=67 < 200 ,x:200
updated_index: 66 , beta[t+1] = beta[66+1] = beta[67]: [6.24859081e-45 1.44268654e-44]
---new i :0 fot index t= 66--
j:0,t=66,i=0,A[i][j]=0.2 ,B[j]: [0.1 0.4 0.5],B_0_2=0.5 x[t]=x[66]: 3, (beta[t+1][j] = beta[67][0]) =6.248590807369812e-45
summation_0_0= 6.2485908073698115e-46
j:1,t=66,i=0,A[i][j]=0.8 ,B[j]: [0.7 0.2 0.1],B_1_2=0.1 x[t]=x[66]: 3, (beta[t+1][j] = beta[67][1]) =1.442686535784287e-44
s

1

In [128]:
beta2

array([[3.45107640e-71, 6.68265148e-71],
       [7.53018444e-71, 1.78041353e-70],
       [2.60354345e-70, 6.15830124e-70],
       [9.01194426e-70, 2.12793628e-69],
       [3.10457855e-69, 7.38420714e-69],
       [1.09093573e-68, 2.51705352e-68],
       [3.52259970e-68, 9.23344699e-68],
       [1.57981898e-67, 2.42847591e-67],
       [1.17494892e-67, 2.77914285e-67],
       [4.06687791e-67, 9.60326407e-67],
       [1.40117888e-66, 3.33212379e-66],
       [4.92142188e-66, 1.13629586e-65],
       [1.59233032e-65, 4.16136445e-65],
       [7.09147585e-65, 1.10397842e-64],
       [8.05140917e-65, 1.23757994e-64],
       [5.97371324e-65, 1.41641695e-64],
       [2.08143985e-64, 4.86534174e-64],
       [6.97272788e-64, 1.73020882e-63],
       [2.73719856e-63, 5.29441166e-63],
       [5.94306913e-63, 1.41359564e-62],
       [2.08854109e-62, 4.81816005e-62],
       [6.74139366e-62, 1.76800215e-61],
       [3.02717241e-61, 4.64277657e-61],
       [2.04035912e-61, 5.33279505e-61],
       [9.089025

In [156]:
for i in range(0,9):
    print(f"{i}")
print("----")
for i in range(2):
    print(i)


0
1
2
3
4
5
6
7
8
----
0
1


In [157]:
def calculate_myGammaw(data,w,A,B, alpha,beta):
    mz = A.shape[0]
    T = data.shape[0]
    print(f"mz:{mz}, T:{T}, alpha : {alpha.shape} , beta : {beta.shape}")
    
    myGamma = np.zeros((mz, mz, T-1))
    print(myGamma.shape)
    # Formula my Gamma  = Summation (alpha_t_i * A(i,j) * beta(t+1, j))
    
    # iterate over T
    for t in range(T-1):
        # calculate gamma values for each pair of hidden states (i,j)
        
        for i in range(mz):
            
            for j in range(mz):
                gamma_t_i_j = alpha[t][i] * A[i][j] * B[j][data[t+1] - 1] * beta[t+1][j]
                myGamma[i][j][t] =gamma_t_i_j
            
    return myGamma
#                 x = data[t-1]
#                 print(f"i : {i} , j: {j}, t: {t}, x : {x}")
#                 # Calculate gamma at time step t for the transition from state i to state j
#                 if t == 1:
#                     alpha_i = w[i] * B[i ,x-1 ]
                    
#                     print(f"alpha_i :{alpha_i}")

        

In [160]:
myGamma = calculate_myGammaw(x,w,A,B, beta2, beta2)

mz:2, T:200, alpha : (200, 2) , beta : (200, 2)
(2, 2, 199)


In [161]:
myGamma

array([[[2.59872418e-142, 1.96051623e-141, 2.34629884e-140,
         2.79782888e-139, 3.38689566e-138, 3.84292988e-137,
         1.11301397e-136, 1.85620659e-135, 4.77837380e-135,
         5.69842343e-134, 6.89579240e-133, 7.83652931e-132,
         2.25839441e-131, 1.14192747e-130, 4.80968095e-130,
         1.24339248e-129, 1.45133136e-128, 1.52685925e-127,
         1.62673602e-126, 1.24123441e-125, 1.40796777e-124,
         4.08147218e-124, 6.17651883e-123, 3.70897520e-123,
         1.85295763e-122, 2.34971600e-122, 9.26268881e-122,
         2.07113598e-121, 1.44870187e-120, 1.09379272e-119,
         1.30427824e-118, 1.57892541e-117, 1.79132408e-116,
         5.18997019e-116, 8.33887706e-115, 1.83024973e-114,
         1.79828639e-113, 1.25930145e-112, 9.47705393e-112,
         1.14683995e-110, 1.30329399e-109, 3.75593816e-109,
         1.89913742e-108, 7.99957357e-108, 2.06775822e-107,
         2.41524849e-106, 2.53443967e-105, 2.75952029e-104,
         1.98327296e-103, 5.74933020e-10

In [165]:
def execute_M_Step_onestep(data, w, A, B, myGamma):
    
    mz,mz,T = myGamma.shape
    print(f"myGamma.shape: {myGamma.shape}")
    M = myGamma
    # Update A ->
    # Calculate the denominator for each i
    denominator = M[:, :, :-1].sum(axis=(2, 1))  # Sum over time steps and j

    # Calculate the numerator for each i and time step
    numerator = M[:, :, :-1].sum(axis=1)  # Sum over j

    # Avoid division by zero by replacing zeros in the denominator with 1
    denominator[denominator == 0] = 1

    # Calculate M*(i, j) using broadcasting
    updated_A = numerator / denominator[:, None]
    
    return updated_A
    
    
#     for i in range(mz):
#         print(f"i: {i} , gamma_i[t,j]")
#         for j in range(mz):
            
#         for t in range(T):
#             sum_neumerator = 0
#             sum_denomenator = 0
#             for j in range(mz):
#                 if sum_neumerator == 0:
#                     sum_neumerator = np.sum(myGamma[i,j,:])
                    
#                 sum_denomenator += np.sum(myGamma[i,:,t])
            
#             print(f"t:{t} , i:{i},sum_neumerator = {sum_neumerator} , sum_denomenator:{sum_denomenator} ")
            
#             sum_denomenator = 0
#             for t in range(T):
#                 sum_denomenator += 
                
    
#     # Update B ->
    
#     pass

In [173]:
def update_A(A, B , gamma):
    mz, mz, t = gamma.shape
    # Perform the iterative operation
    A_updated = np.zeros_like(A)
    for i in range(mz):
        for j in range(mz):
            denominator = 0
            for j_prime in range(mz):
                for time_step in range(t - 1):
                    denominator += gamma[i, j_prime, time_step]

            for time_step in range(t - 1):
                numerator = 0
                for j_prime in range(mz):
                    numerator += gamma[i, j_prime, time_step]

                A_updated[i, j] = numerator / denominator
    return A_updated


In [174]:
updated_A = execute_M_Step_onestep(x, w, A, B, myGamma)

myGamma.shape: (2, 2, 199)


In [175]:
updated_A.shape

(2, 198)

In [176]:
A_updated = update_A(A,B, myGamma)

In [177]:
A_updated

array([[0.93388916, 0.93388916],
       [0.89172706, 0.89172706]])

In [187]:
def update_B( B , gamma):
    mz, mz, t = gamma.shape
    mx = B.shape[1]
    # Perform the iterative operation
    B_updated = np.zeros_like(B)
    
    # Calculate the updated B matrix
    for i in range(mz):
        for l in range(mx):
            print(f" i : {i} , l :{l}")
            numerator = myGamma[:, :, l].sum()  # Sum over t where x(t) = l
            denominator = myGamma[i, :, :].sum()  # Sum over t

            # Avoid division by zero by replacing zeros in the denominator with 1
            if denominator == 0:
                denominator = 1

            B_updated[i, l] = numerator / denominator
    
    return B_updated

In [188]:
B_updated = update_B(B, myGamma)

 i : 0 , l :0
 i : 0 , l :1
 i : 0 , l :2
 i : 1 , l :0
 i : 1 , l :1
 i : 1 , l :2


In [189]:
B_updated

array([[6.14212734e-141, 5.37742383e-140, 6.43383562e-139],
       [6.13591093e-141, 5.37198137e-140, 6.42732397e-139]])

In [183]:
for i in range(2):
    print(i)

0
1


In [184]:
B.shape

(2, 3)

In [185]:
gamma_1 = myGamma[:,:,1]

In [186]:
gamma_1

array([[1.96051623e-141, 3.70985153e-141],
       [1.39061519e-140, 4.38572913e-141]])